export const quantumKeywords = [
    "量子",
    "Quantum",
    "量子コンピュータ",
    "Quantum Computer",
    "量子コンピューティング",
    "Quantum Computing",
    "量子情報",
    "Quantum Information",
    "量子力学",
    "Quantum Mechanics",
    "Qiskit",
    "量子学習",
    "Quantum Learning",
    "日本語訳",
    "日本語",
    "訳",
    "Japanese",
];
